version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - setup
      - run:
          name: Login to QUAY.IO
          command: |
            docker login quay.io -u $QUAY_USER -p $QUAY_PASS
      - run:
          name: Build multiarch docker image and push
          command: |
            docker buildx build --platform linux/ppc64le,linux/s390x,linux/arm64,linux/amd64 --push -t quay.io/mayurwaghmode111/circleci-multi-arch .
workflows:
  version: 2.1
  build-and-push-multi-arch-image:
    jobs:
      - build
